fail_fast: true

repos:
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -   id: black
        name: "Black format checker"
        args: ["--check"]
        language_version: python3
