fail_fast: true

repos:
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -   id: black
        name: "Black format checker (source)"
        args: ["--check"]
        files: ^src/
        types: [file, python]
        language: python
    -   id: black
        name: "Black format checker (tests)"
        args: ["--check"]
        files: ^tests/
        types: [file, python]
        language: python
